#!/bin/sh
#
# Copyright (C) 2010-2012 Ian Moore <imooreyahoo@gmail.com>
# Copyright (C) 2013-2014 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

TS_MANAGEMENT_SITE_CONF="/etc/nginx/openmediavault-webgui.d/openmediavault-ts3.conf"

if [ -e "${TS_MANAGEMENT_SITE_CONF}" ]; then
    rm ${TS_MANAGEMENT_SITE_CONF}
fi

if [ "$(omv_config_get " /config/services/teamspeak3/enable")" != "1" ]; then
    exit 0
fi

if [ "$(omv_config_get " /config/services/teamspeak3/enablewi")" != "1" ]; then
    exit 0
fi

cat <<EOF > "${TS_MANAGEMENT_SITE_CONF}"
location /ts3wi/ {
    alias /usr/share/ts3wi/;
    index index.php;
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php5-fpm-openmediavault-ts3.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }
    location = /ts3wi/favicon.ico {
        log_not_found off;
        access_log off;
    }
    location = /ts3wi/robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
    location /ts3wi/ {
        try_files \$uri \$uri/ /ts3wi/index.php?\$args;
    }
    location ~ /ts3wi/\. {
        deny all;
    }
    location ~* /ts3wi/(?:config)/.*\.php$ {
        deny all;
    }
    location ~* /ts3wi/\.(js|css|png|jpg|jpeg|gif|ico)$ {
        expires max;
        log_not_found off;
    }
}
EOF

exit 0

