#!/bin/sh
# @license http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author Volker Theile <volker.theile@openmediavault.org>
# @author OpenMediaVault Plugin Developers <plugins@omvextras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2017 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        # Set the default settings of the service package to those expected by
        # OpenMediaVault.
        if [ -z "${2}" ]; then
            systemctl stop teamspeak3.service
            systemctl disable teamspeak3.service
        fi

        SERVICE_XPATH_NAME="teamspeak3"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if [ ! -d /opt/teamspeak3 ] && getent passwd ts3 >/dev/null 2>&1; then
            userdel ts3 >/dev/null
        fi

        if ! getent passwd ts3 >/dev/null 2>&1; then
            adduser --quiet \
                    --system \
                    --ingroup nogroup \
                    --no-create-home \
                    --disabled-password \
                    --gecos "" \
                    ts3
        fi
        
        chmod 0440 /etc/sudoers.d/ts3
        chmod 644 /etc/ld.so.conf.d/ts3libs.conf

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_add_node "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_key "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_key "${SERVICE_XPATH}" "password" ""
            omv_config_add_key "${SERVICE_XPATH}" "queryport" "10011"
            omv_config_add_key "${SERVICE_XPATH}" "vsport" "9987"
            omv_config_add_key "${SERVICE_XPATH}" "fileport" "30033"
            omv_config_add_key "${SERVICE_XPATH}" "update" "0"
            omv_config_add_key "${SERVICE_XPATH}" "restartmsg" ""
            omv_config_add_key "${SERVICE_XPATH}" "eula" "0"
            omv_config_add_key "${SERVICE_XPATH}" "enablewi" "0"
            omv_config_add_key "${SERVICE_XPATH}" "languagewi" "en"
        fi

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
