#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        rm -Rf /opt/teamspeak3 & >/dev/null

        if [ -f "/opt/teamspeak3/ts3server.pid" ]; then
            PID=$(cat /var/run/teamspeak3/ts3server.pid);
            kill -0 $PID 2>/dev/null;

            if [ $? -eq 0 ]; then
                kill -9 $PID;
            fi
        fi

        omv_config_delete "//services/teamspeak3"

        if [ -d "/opt/teamspeak3" ]; then
            rm -Rf /opt/teamspeak3/* &>/dev/null
        fi

        userdel -r ts3

        if [ ! -d /opt ]; then
            mkdir /opt
            chmod 775 /opt
        fi
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
