#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_TS3_CONFIG=/etc/php5/fpm/pool.d/openmediavault-ts3.conf

case "$1" in
    configure)
        if ! getent passwd ts3 >/dev/null 2>&1; then
            echo "Adding teamspeak3 user..."
            useradd --create-home --groups users --no-user-group --shell /usr/sbin/nologin ts3
            insserv -d teamspeak3
        else
            echo "ts3 user already exists."
        fi

        # Create TS3 fpm config file
        if [ ! -f ${OMV_TS3_CONFIG} ]; then
            cat <<EOF > ${OMV_TS3_CONFIG}
[openmediavault-ts3]
listen = /var/run/php5-fpm-openmediavault-ts3wi.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0600

user = www-data
group = www-data

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

php_value[post_max_size] = 25M
php_value[upload_max_filesize] = 25M
EOF
        service php5-fpm reload >/dev/null 2>&1
        fi

        chmod 775 /opt
        chown root:users /opt

        if ! omv_config_exists "/config/services/teamspeak3"; then
            echo "Initial configuration."
            object="<enable>0</enable>"
            object="${object}<password></password>"
            object="${object}<queryport>10011</queryport>"
            object="${object}<vsport>9987</vsport>"
            object="${object}<fileport>30033</fileport>"
            object="${object}<update></update>"
            object="${object}<restartmsg></restartmsg>"
            object="${object}<eula>0</eula>"
            object="${object}<enablewi>0</enablewi>"
            object="${object}<languagewi>en</languagewi>"
            omv_config_add_element "/config/services" "teamspeak3" "${object}" true
        fi
        
        omv_install_fixperms

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
