#!/bin/sh
# @license http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author Volker Theile <volker.theile@openmediavault.org>
# @author OpenMediaVault Plugin Developers <plugins@omvextras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2017 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)

        if [ -f "/opt/teamspeak3/ts3server.pid" ]; then
            PID=$(cat /opt/teamspeak3/ts3server.pid);
            kill -0 $PID 2>/dev/null || :;

            if [ $? -eq 0 ]; then
                kill -9 $PID || :;
            fi
        fi

        omv_config_delete "/config/services/teamspeak3"

        if [ -d "/opt/teamspeak3" ]; then
            rm -rf /opt/teamspeak3 &>/dev/null
        fi

        if getent passwd ts3 >/dev/null 2>&1; then
            userdel ts3
        fi

        if [ -d /usr/share/ts3wi ]; then
            rm -rf /usr/share/ts3wi
        fi
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
